In [1]:
import numpy as np

In [2]:
x = np.array([
    [1, 0, 1, 1],
    [0, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 1, 1, 0]
])

In [3]:
w = np.array([
    [0.9, 0.3, 0.1, 0.2],
    [0.1, 0.6, 0.2, 0.1]
])

In [6]:

# Learning rate
lr = 0.1

# Number of epochs
epochs = 2

for e in range(epochs):

    print(f"\nEpoch {e+1}")

    for i in range(len(x)):

        print("\nInput Vector:", x[i])

        # Calculate Euclidean Distance
        distances = np.sum((w - x[i])**2, axis=1)

        print("Distances:", distances)

        # Find Best Matching Unit (BMU)
        bmu = np.argmin(distances)

        print("Winning Neuron:", bmu + 1)

        # Update winning neuron's weights
        w[bmu] = w[bmu] + lr * (x[i] - w[bmu])

        print("Updated Weights:")
        print(w)

    # Reduce learning rate
    lr = lr * 0.5

print("\nFinal Weights:")
print(w)


Epoch 1

Input Vector: [1 0 1 1]
Distances: [0.72189351 2.22513897]
Winning Neuron: 1
Updated Weights:
[[0.96339895 0.3019625  0.49302955 0.51503225]
 [0.07408842 0.44453053 0.14817684 0.3332042 ]]

Input Vector: [0 0 0 1]
Distances: [1.49759075 0.6696695 ]
Winning Neuron: 2
Updated Weights:
[[0.96339895 0.3019625  0.49302955 0.51503225]
 [0.06667958 0.40007748 0.13335916 0.39988378]]

Input Vector: [1 0 0 1]
Distances: [0.57079285 1.40907313]
Winning Neuron: 1
Updated Weights:
[[0.96705906 0.27176625 0.44372659 0.56352902]
 [0.06667958 0.40007748 0.13335916 0.39988378]]

Input Vector: [1 1 1 0]
Distances: [1.15841456 2.14196743]
Winning Neuron: 1
Updated Weights:
[[0.97035315 0.34458963 0.49935394 0.50717612]
 [0.06667958 0.40007748 0.13335916 0.39988378]]

Epoch 2

Input Vector: [1 0 1 1]
Distances: [0.6131428  2.14235482]
Winning Neuron: 1
Updated Weights:
[[0.97183549 0.32736015 0.52438624 0.53181732]
 [0.06667958 0.40007748 0.13335916 0.39988378]]

Input Vector: [0 0 0 1]
Distanc